export type Variant = "italian" | "chinese";

export interface Product {
  id: string;
  images: string[];
  applications: string[];
  nameAr: string;
  nameEn: string;
  type: Variant;
  tag: "slab" | "vanity" | "countertop";
  finishAr: string;
  finishEn: string;
  size: string;
}

export const imagesGlob = import.meta.glob('/src/assets/**/*.{jpg,jpeg,png,webp}', { eager: true, query: '?url', import: 'default' }) as Record<string, string>;

export const productsData: Product[] = [
  { id: "001", nameEn: "Alice Gold", nameAr: "أليس جولد", images: ["/src/assets/Alice Gold/173743175615090.jpg","/src/assets/Alice Gold/173743178630656.jpg","/src/assets/Alice Gold/173743178662541.jpg","/src/assets/Alice Gold/Alice Gold Polshied.webp","/src/assets/Alice Gold/Alice Gold Polshied1.webp","/src/assets/Alice Gold/Alice Gold Polshied2.webp","/src/assets/Alice Gold/173743178629482.jpg"], applications: ["/src/assets/Alice Gold/Alice Gold Polshied1.webp","/src/assets/Alice Gold/Alice Gold Polshied2.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "002", nameEn: "Arbeescato", nameAr: "ارابيسكاتو", images: ["/src/assets/Arbeescato/Arbeescato.webp","/src/assets/Arbeescato/Arbeescato2.webp"], applications: ["/src/assets/Arbeescato/Arbeescato2.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "003", nameEn: "ARCTIC OCEAN", nameAr: "أركتيك أوشن", images: ["/src/assets/ARCTIC OCEAN/173743892495717.jpg","/src/assets/ARCTIC OCEAN/ARCTIC OCEAN.webp","/src/assets/ARCTIC OCEAN/ARCTIC OCEAN1.webp","/src/assets/ARCTIC OCEAN/173743892445976.jpg"], applications: ["/src/assets/ARCTIC OCEAN/ARCTIC OCEAN1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "004", nameEn: "Armani Dark Grey", nameAr: "أرماني رمادي غامق", images: ["/src/assets/Armani Dark Grey/Armani Dark Grey.webp","/src/assets/Armani Dark Grey/Armani Dark Grey1.webp"], applications: ["/src/assets/Armani Dark Grey/Armani Dark Grey1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "005", nameEn: "Bouique Calartte Gold", nameAr: "بوتيك كلكتا جولد", images: ["/src/assets/Bouique Calartte Gold/Screenshot 2026-07-04 091532.png"], applications: [], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "006", nameEn: "Bvlgari Black", nameAr: "بولغاري أسود", images: ["/src/assets/Bvlgari Black/173744051823362.jpg","/src/assets/Bvlgari Black/Bvlgari Black.webp","/src/assets/Bvlgari Black/Bvlgari Black1.webp","/src/assets/Bvlgari Black/Bvlgari Black2.webp","/src/assets/Bvlgari Black/Bvlgari Black3.webp","/src/assets/Bvlgari Black/Bvlgari Black4.webp","/src/assets/Bvlgari Black/173744051821022.jpg"], applications: ["/src/assets/Bvlgari Black/Bvlgari Black1.webp","/src/assets/Bvlgari Black/Bvlgari Black2.webp","/src/assets/Bvlgari Black/Bvlgari Black3.webp","/src/assets/Bvlgari Black/Bvlgari Black4.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "007", nameEn: "Calactta Gold-X", nameAr: "كلكتا جولد إكس", images: ["/src/assets/Calactta Gold-X/173743736951339.jpg","/src/assets/Calactta Gold-X/Calactta Gold-X.webp","/src/assets/Calactta Gold-X/Calartte Gold.webp","/src/assets/Calactta Gold-X/173743736957969.jpg","/src/assets/Calactta Gold-X/Calartte Gold 1.webp"], applications: ["/src/assets/Calactta Gold-X/Calartte Gold 1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "008", nameEn: "Calctta Macchia Vecchia", nameAr: "كلكتا ماكيا فيكيا", images: ["/src/assets/Calctta Macchia Vecchia/173743884852947.jpg","/src/assets/Calctta Macchia Vecchia/173743884892473.jpg","/src/assets/Calctta Macchia Vecchia/178269831013293.jpg","/src/assets/Calctta Macchia Vecchia/178269840447508.jpg","/src/assets/Calctta Macchia Vecchia/Calctta Macchia Vecchia.webp","/src/assets/Calctta Macchia Vecchia/Calctta Macchia Vecchia1.webp","/src/assets/Calctta Macchia Vecchia/173743884829006.jpg","/src/assets/Calctta Macchia Vecchia/174987085059849.jpg"], applications: ["/src/assets/Calctta Macchia Vecchia/Calctta Macchia Vecchia1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "009", nameEn: "CHARM  IVORY", nameAr: "تشارم آيفوري", images: ["/src/assets/CHARM  IVORY/CHARM  IVORY.webp","/src/assets/CHARM  IVORY/CHARM  IVORY1.webp","/src/assets/CHARM  IVORY/CHARM  IVORY2.webp"], applications: ["/src/assets/CHARM  IVORY/CHARM  IVORY1.webp","/src/assets/CHARM  IVORY/CHARM  IVORY2.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "010", nameEn: "CRISTALLO AMBRA", nameAr: "كريستالو أمبرا", images: ["/src/assets/CRISTALLO AMBRA/178271627311809.jpg","/src/assets/CRISTALLO AMBRA/178271627354144.jpg","/src/assets/CRISTALLO AMBRA/178271647661775.jpg","/src/assets/CRISTALLO AMBRA/CRISTALLO AMBRA.webp","/src/assets/CRISTALLO AMBRA/178271483875811.jpg"], applications: ["/src/assets/CRISTALLO AMBRA/1 (2).png","/src/assets/CRISTALLO AMBRA/1-1.png"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "011", nameEn: "GOLD JADE", nameAr: "جولد جيد", images: ["/src/assets/GOLD JADE/GOLD JADE.webp","/src/assets/GOLD JADE/GOLD JADE1.webp"], applications: ["/src/assets/GOLD JADE/GOLD JADE1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "012", nameEn: "GREEK WHITE", nameAr: "جريك وايت", images: ["/src/assets/GREEK WHITE/GREEK WHITE.webp","/src/assets/GREEK WHITE/GREEK WHITE1.webp","/src/assets/GREEK WHITE/GREEK WHITE2.webp","/src/assets/GREEK WHITE/GREEK WHITE3.webp"], applications: ["/src/assets/GREEK WHITE/GREEK WHITE1.webp","/src/assets/GREEK WHITE/GREEK WHITE2.webp","/src/assets/GREEK WHITE/GREEK WHITE3.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "013", nameEn: "Laurent White", nameAr: "لوران وايت", images: ["/src/assets/Laurent White/Laurent White1.webp","/src/assets/Laurent White/Laurent White.webp"], applications: ["/src/assets/Laurent White/Laurent White1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "014", nameEn: "MARMO BRUNO PERLA", nameAr: "مارمو برونو بيرلا", images: ["/src/assets/MARMO BRUNO PERLA/MARMO BRUNO PERLA.webp","/src/assets/MARMO BRUNO PERLA/MARMO BRUNO PERLA1.webp"], applications: ["/src/assets/MARMO BRUNO PERLA/MARMO BRUNO PERLA1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "015", nameEn: "Patagonia", nameAr: "باتاغونيا", images: ["/src/assets/Patagonia/173744124013524.jpg","/src/assets/Patagonia/173744124016562.jpg","/src/assets/Patagonia/173744124088693.jpg","/src/assets/Patagonia/173744124090523.jpg","/src/assets/Patagonia/173744126966594.jpg","/src/assets/Patagonia/173744127042868.jpg","/src/assets/Patagonia/Patagonia.webp","/src/assets/Patagonia/173744124951239.jpg","/src/assets/Patagonia/173744127019181.jpg"], applications: ["/src/assets/Patagonia/2 (2).png"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "016", nameEn: "port Laurent", nameAr: "بورت لوران", images: ["/src/assets/port Laurent/173744137091347.jpg","/src/assets/port Laurent/port Laurent.webp","/src/assets/port Laurent/173744137035982.jpg"], applications: ["/src/assets/port Laurent/3 (2).png"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "017", nameEn: "Shakespeare Black", nameAr: "شكسبير بلاك", images: ["/src/assets/Shakespeare Black/Shakespeare Black.webp","/src/assets/Shakespeare Black/Shakespeare Black1.webp"], applications: ["/src/assets/Shakespeare Black/Shakespeare Black1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "018", nameEn: "Statuario Gold", nameAr: "ستاتيواريو جولد", images: ["/src/assets/Statuario Gold/173743734422380.jpg","/src/assets/Statuario Gold/Statuario Gold.webp","/src/assets/Statuario Gold/Statuario Goldd1.webp","/src/assets/Statuario Gold/173743734493276.jpg","/src/assets/Statuario Gold/Statuario Gold2.webp"], applications: ["/src/assets/Statuario Gold/Statuario Goldd1.webp","/src/assets/Statuario Gold/Statuario Gold2.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "019", nameEn: "Statuario White", nameAr: "ستاتيواريو وايت", images: ["/src/assets/Statuario White/Statuario White.webp","/src/assets/Statuario White/Statuario Whitee.webp"], applications: ["/src/assets/Statuario White/Statuario Whitee.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "020", nameEn: "TAJ MAHAL", nameAr: "تاج محل", images: ["/src/assets/TAJ MAHAL/173744211331524.jpg","/src/assets/TAJ MAHAL/TAJ MAHAL.webp","/src/assets/TAJ MAHAL/TAJ MAHAL1.webp","/src/assets/TAJ MAHAL/173744211921987.jpg"], applications: ["/src/assets/TAJ MAHAL/TAJ MAHAL1.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "021", nameEn: "TRAVERTINO ROMANO", nameAr: "ترافنتينو رومانو", images: ["/src/assets/TRAVERTINO ROMANO/TRAVERTINO ROMANO.webp","/src/assets/TRAVERTINO ROMANO/TRAVERTINO ROMANO1.webp","/src/assets/TRAVERTINO ROMANO/TRAVERTINO ROMANO2.webp"], applications: ["/src/assets/TRAVERTINO ROMANO/TRAVERTINO ROMANO1.webp","/src/assets/TRAVERTINO ROMANO/TRAVERTINO ROMANO2.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" },
  { id: "022", nameEn: "Wooden", nameAr: "خشبي وودن", images: ["/src/assets/Wooden/Wooden.webp","/src/assets/Wooden/Wooden1.webp","/src/assets/Wooden/Wooden2.webp","/src/assets/Wooden/Wooden3.webp","/src/assets/Wooden/Wooden4.webp"], applications: ["/src/assets/Wooden/Wooden1.webp","/src/assets/Wooden/Wooden2.webp","/src/assets/Wooden/Wooden3.webp","/src/assets/Wooden/Wooden4.webp"], tag: "slab", type: "chinese", finishAr: "مصقول لامع", finishEn: "Polished", size: "1600 X 3200mm X 12mm" }
];
